server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  user: root
  password: www.184WYOP.com
  dbname: kuonji_new
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  auto_migrate: false

redis:
  host: 8.218.174.69
  port: 6379
  password: 231310627
  db: 0

jwt:
  secret: kuonji_new
  expire: 24h

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin123}
  email: ${ADMIN_EMAIL:admin@example.com}

log:
  level: info
  format: json
  output: stdout
